name: Deploy api backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'api/**'

jobs:
  deploy_back:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: 'gouvx-427422'
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        source: 'api'
        service: 'gouvx-api'
        env_vars: 'OPENAI_API_KEY=${{secrets.OPENAI_API_KEY}}, PINECONE_API_KEY=${{secrets.PINECONE_API_KEY}}, RUNPOD_ENDPOINT_ID=${{secrets.RUNPOD_ENDPOINT_ID}}, RUNPOD_API_KEY=${{secrets.RUNPOD_API_KEY}}'
